# =============================================================================
# ExamCraft Frontend - Production Docker Compose (Based on Working Dev Version)
# =============================================================================
# This Docker Compose configuration is based on the working development version
# but adapted for production with:
# - Production Dockerfile and environment
# - No volume mounts (built into image)
# - Production environment variables
# - Same reliable structure as development
# =============================================================================

# Version attribute removed (obsolete in modern Docker Compose)

services:
  # ---------------------------------------------------------------------------
  # ExamCraft Frontend Service
  # ---------------------------------------------------------------------------
  examcraft-frontend:
    # Build configuration - CHANGED TO PRODUCTION DOCKERFILE
    build:
      context: .
      dockerfile: Dockerfile

    # Container name for production
    container_name: examcraft-frontend-prod
    dns:
      - 8.8.8.8
      - 8.8.4.4
    # Port mapping (host:container)
    ports:
      - "3000:3000"

    # Environment variables for production
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Supabase configuration (loaded from .env.docker)
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}

    # Environment file for production
    env_file:
      - .env.production

    # No volume mounts for production (built into image)

    # Restart policy for production
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Production labels
    labels:
      - "com.examcraft.environment=production"
      - "com.examcraft.service=frontend"
      - "com.examcraft.version=prod"

# -----------------------------------------------------------------------------
# Networks (Optional: Create custom network for future services)
# -----------------------------------------------------------------------------
networks:
  default:
    name: examcraft-prod-network
    driver: bridge

# -----------------------------------------------------------------------------
# Volumes (Optional: Named volumes for persistent data)
# -----------------------------------------------------------------------------
volumes:
  node_modules:
    driver: local
  next_cache:
    driver: local
